spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: mongo-client
  profiles:
    active: test

management.endpoints.web.exposure.include: env, health, info, refresh
